services:
  backend:
    build: ./backend
    ports:
      - "3001:3001"
    environment:
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SESSION_SECRET=${SESSION_SECRET}
      - PORT=3001
      - FRONTEND_URL=http://localhost:3000
      - BACKEND_URL=http://localhost:3001
    volumes:
      - ./backend:/app
      - /app/node_modules
    
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:3001 